name: loginapp
description: A Flutter project for login functionality with registration and index screens.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Define the version and build number for the app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Declare the assets folder for images
  assets:
    - assets/images/
